name: 버그 리포트
description: 이 스크립트를 개선할 수 있도록, 버그가 있다면 알려주세요.
title: "[BUG] "

body:
- type: checkboxes
  id: confirmationskr
  attributes:
    label: 잠깐! 버그 리포트를 작성하기 전에-
    description: 아래의 항목을 먼저 확인해보세요. 아래의 사항을 확인해 보는 것만으로 일반적인 문제가 해결될 수도 있습니다.
    options:
      - label: 해당 스크립트는 최신 버전을 사용합니다.
        required: true
      - label: 해당 스크립트가 지원하는 AE 버전을 사용합니다.
        required: true
      - label: 해당 스크립트는 불법 배포망에서 받지 않은 정품입니다.
        required: true
      - label: 해당 스크립트는 제3자가 수정하지 않은 오리지널 버전입니다.